export const CHANGE_MAINDATA = 'CHANGE_MAINDATA';
export const CHANGE_INDEX = 'CHANGE_INDEX';
export const CHANGE_LISTITEMDATA = 'CHANGE_LISTITEMDATA';
export const CHANGE_UPLOADING = 'CHANGE_UPLOADING';

export const CHANGE_DOWNLOADING = 'CHANGE_DOWNLOADING';
export const CHANGE_LIST_OFFSET = 'CHANGE_LIST_OFFSET';